include:
  - project: "pub/numeco/m4g/ci-library"
    ref: main
    file: "/stages/build/build-image-kaniko.yml"
  - project: "pub/numeco/m4g/ci-library"
    ref: main
    file: "/stages/analysis/mte-image-scan.yml"
#  - project: "pub/numeco/m4g/ci-library"
#    ref: main
#    file: "/stages/analysis/sonarqube.yml"


stages:
  - build-image
#  - analysis
